AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
Resources:
  hello:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.hello
      Runtime: nodejs8.10
      CodeUri: s3://awssamsample/96e724bf2090d0c5fba4f8b14abe5a8e
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 512
      Timeout: 10
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /hello
            Method: ANY
